// DO NOT EDIT — generated by scripts/generate_sdk_scope_constants.py
// Source: docs/platform/scopes.yaml + docs/platform/roles.yaml
// Regenerate via `python3 scripts/generate_sdk_scope_constants.py`.

#![allow(non_upper_case_globals)]

/// Every role in the Olympus Cloud platform catalog.
pub struct OlympusRoles;
impl OlympusRoles {
    /// Break-glass root. Emergency-only. All platform scopes.
    pub const SUPER_ADMIN: &'static str = "super_admin";
    /// System-level administrative access across all tenants. Used by internal SREs.
    pub const SYSTEM_ADMIN: &'static str = "system_admin";
    /// Day-to-day platform operations — tenant CRUD, app install review, HITL approvals.
    pub const PLATFORM_OPERATOR: &'static str = "platform_operator";
    /// Platform administrative role for product + developer-experience operations.
    pub const PLATFORM_ADMIN: &'static str = "platform_admin";
    /// Full control of a single tenant — user management, app installs, billing, settings.
    pub const TENANT_ADMIN: &'static str = "tenant_admin";
    /// Tenant billing/legal owner. Often same person as tenant_admin but tracked separately for compliance.
    pub const TENANT_OWNER: &'static str = "tenant_owner";
    /// Operational manager within a tenant — staff management, reporting, non-billing settings.
    pub const MANAGER: &'static str = "manager";
    /// Shift supervisor — can approve overrides, adjust orders, view team reports.
    pub const SUPERVISOR: &'static str = "supervisor";
    /// Line-level staff — POS, kitchen, counter. Read-only on reports by default.
    pub const STAFF: &'static str = "staff";
    /// Baseline tenant-attached identity with no operational role. Customers, guests, invited users before role assignment.
    pub const USER: &'static str = "user";
    /// Restaurant GM/FOH-manager — menu, staff, reservations, POS overrides.
    pub const RESTAURANT_MANAGER: &'static str = "restaurant_manager";
    /// Bar-vertical staff — dram-shop compliance, age verification workflows.
    pub const BARTENDER: &'static str = "bartender";
    /// Delivery driver — route/order assignment, geofence pickup.
    pub const DRIVER: &'static str = "driver";
    /// Admin of an installed app's own configuration (app-level settings, not tenant settings).
    pub const APP_ADMIN: &'static str = "app_admin";
    /// Baseline user interacting with an installed app without admin powers.
    pub const APP_USER: &'static str = "app_user";
    /// Device principal (POS terminal, kiosk, KDS). Subject format `device:<uuid>`. Calls are bounded to registered device surface.
    pub const DEVICE: &'static str = "device";
}

pub const OLYMPUS_ROLES_ALL: [&str; 16] = [
    "super_admin",
    "system_admin",
    "platform_operator",
    "platform_admin",
    "tenant_admin",
    "tenant_owner",
    "manager",
    "supervisor",
    "staff",
    "user",
    "restaurant_manager",
    "bartender",
    "driver",
    "app_admin",
    "app_user",
    "device",
];

/// Roles that grant global platform control. Matches `backend/rust/platform/src/middleware/rbac.rs:PLATFORM_ADMIN_ROLES`.
pub const PLATFORM_ADMIN_ROLES: [&str; 4] = [
    "platform_admin",
    "platform_operator",
    "system_admin",
    "super_admin",
];

/// Roles that can manage tenant-scoped resources. Matches `TENANT_ADMIN_ROLES` in Rust middleware.
pub const TENANT_ADMIN_ROLES: [&str; 6] = [
    "tenant_admin",
    "tenant_owner",
    "platform_admin",
    "platform_operator",
    "system_admin",
    "super_admin",
];

/// Roles that can operate tenant resources (managers, supervisors, admins). Matches `TENANT_OPERATOR_ROLES` in Rust middleware.
pub const TENANT_OPERATOR_ROLES: [&str; 9] = [
    "manager",
    "supervisor",
    "restaurant_manager",
    "tenant_admin",
    "tenant_owner",
    "platform_admin",
    "platform_operator",
    "system_admin",
    "super_admin",
];
