// DO NOT EDIT — generated by scripts/generate_sdk_scope_constants.py
// Source: docs/platform/scopes.yaml + docs/platform/roles.yaml
// Regenerate via `python3 scripts/generate_sdk_scope_constants.py`.

#![allow(non_upper_case_globals)]

/// Every scope in the Olympus Cloud platform catalog.
pub struct OlympusScopes;
impl OlympusScopes {
    /// List the caller's active sessions.
    pub const AUTH_SESSION_READ_AT_USER: &'static str = "auth.session.read@user";
    /// Revoke one of the caller's own sessions.
    pub const AUTH_SESSION_DELETE_AT_USER: &'static str = "auth.session.delete@user";
    /// Enroll, update, or disable the caller's MFA factors.
    pub const AUTH_MFA_WRITE_AT_USER: &'static str = "auth.mfa.write@user";
    /// Read the caller's tenant metadata (name, plan, hierarchy position).
    pub const PLATFORM_TENANT_READ_AT_TENANT: &'static str = "platform.tenant.read@tenant";
    /// Update tenant-level settings (display name, locale, default brand).
    pub const PLATFORM_TENANT_WRITE_AT_TENANT: &'static str = "platform.tenant.write@tenant";
    /// Grant/revoke tenant administrators, rotate tenant keys, close tenant.
    pub const PLATFORM_TENANT_ADMIN_AT_TENANT: &'static str = "platform.tenant.admin@tenant";
    /// Create a new tenant via the platform provisioning API (platform-admin path).
    pub const PLATFORM_TENANT_CREATE_AT_TENANT: &'static str = "platform.tenant.create@tenant";
    /// Self-service tenant creation for email-verified Firebase users (marketing-site signup funnel).
    pub const PLATFORM_TENANT_SELFSERVICE_AT_USER: &'static str = "platform.tenant.selfservice@user";
    /// Update tenant lifecycle metadata (plan, billing address, tax id) via the canonical /tenant/current PATCH surface.
    pub const PLATFORM_TENANT_LIFECYCLE_AT_TENANT: &'static str = "platform.tenant.lifecycle@tenant";
    /// Retire (soft-delete) a tenant. 30-day grace window; requires MFA and typed confirmation slug.
    pub const PLATFORM_TENANT_RETIRE_AT_TENANT: &'static str = "platform.tenant.retire@tenant";
    /// Read the caller's tenant runtime config bundle — branding, feature flags, locale strings, resolved policy overrides.
    pub const PLATFORM_TENANT_CONFIG_READ_AT_USER: &'static str = "platform.tenant.config.read@user";
    /// Update the tenant runtime config bundle (brand URLs, locale overrides, extension key/values). Tenant-admin + MFA required.
    pub const PLATFORM_TENANT_CONFIG_WRITE_AT_TENANT: &'static str = "platform.tenant.config.write@tenant";
    /// Install an Olympus app onto the tenant (creates pending-install, awaits consent).
    pub const PLATFORM_APPS_INSTALL_AT_TENANT: &'static str = "platform.apps.install@tenant";
    /// Read the list of apps installed into the tenant and their granted scopes.
    pub const PLATFORM_APPS_INSTALL_READ_AT_TENANT: &'static str = "platform.apps.install.read@tenant";
    /// Uninstall an app and revoke all of its granted scopes. Revocation is immediate and cannot be undone without re-installing.
    pub const PLATFORM_APPS_UNINSTALL_AT_TENANT: &'static str = "platform.apps.uninstall@tenant";
    /// Read an app's manifest (name, publisher, required/optional scopes, privacy/tos URLs) from the platform catalog.
    pub const PLATFORM_APPS_MANIFEST_AT_USER: &'static str = "platform.apps.manifest@user";
    /// Read a decrypted tenant-scoped secret value (or metadata only with reveal=false). Requires recent MFA.
    pub const PLATFORM_TENANT_SECRET_READ_AT_TENANT: &'static str = "platform.tenant.secret.read@tenant";
    /// Create or rotate a tenant-scoped secret value. Requires recent MFA; bumps version on every call.
    pub const PLATFORM_TENANT_SECRET_WRITE_AT_TENANT: &'static str = "platform.tenant.secret.write@tenant";
    /// Permanently remove a tenant-scoped secret. Requires recent MFA.
    pub const PLATFORM_TENANT_SECRET_DELETE_AT_TENANT: &'static str = "platform.tenant.secret.delete@tenant";
    /// List the keys (never values) of tenant-scoped secrets. No MFA — key names alone reveal no sensitive data.
    pub const PLATFORM_TENANT_SECRET_LIST_READ_AT_USER: &'static str = "platform.tenant.secret.list.read@user";
    /// Create an identity invite (manager + tenant-admin). Sends a signed invite-token for the invitee to attach their Firebase identity.
    pub const PLATFORM_IDENTITY_INVITE_WRITE_AT_TENANT: &'static str = "platform.identity.invite.write@tenant";
    /// Accept an identity invite by attaching a Firebase ID token to the invite's platform identity.
    pub const PLATFORM_IDENTITY_INVITE_ACCEPT_AT_USER: &'static str = "platform.identity.invite.accept@user";
    /// Remove a user from a tenant (revokes roles + location bindings). The user's underlying Firebase identity is preserved.
    pub const PLATFORM_IDENTITY_REMOVE_FROM_TENANT_AT_TENANT: &'static str = "platform.identity.remove_from_tenant@tenant";
    /// Exchange a Firebase ID token for an Olympus access token (federated login).
    pub const PLATFORM_FIREBASE_EXCHANGE_EXECUTE_AT_TENANT: &'static str = "platform.firebase.exchange.execute@tenant";
    /// Link a Firebase identity to the authenticated Olympus user.
    pub const PLATFORM_FIREBASE_LINK_EXECUTE_AT_USER: &'static str = "platform.firebase.link.execute@user";
    /// Read the caller's profile (name, email, avatar, preferences).
    pub const PLATFORM_USER_PROFILE_READ_AT_USER: &'static str = "platform.user.profile.read@user";
    /// Update the caller's profile.
    pub const PLATFORM_USER_PROFILE_WRITE_AT_USER: &'static str = "platform.user.profile.write@user";
    /// List users in the tenant.
    pub const PLATFORM_USER_READ_AT_TENANT: &'static str = "platform.user.read@tenant";
    /// Invite or update users in the tenant.
    pub const PLATFORM_USER_WRITE_AT_TENANT: &'static str = "platform.user.write@tenant";
    /// Remove a user from the tenant (soft-delete; GDPR-safe).
    pub const PLATFORM_USER_DELETE_AT_TENANT: &'static str = "platform.user.delete@tenant";
    /// Grant or revoke role-derived scopes for a user in this tenant.
    pub const PLATFORM_USERS_ROLES_ASSIGN_EXECUTE_AT_TENANT: &'static str = "platform.users.roles.assign.execute@tenant";
    /// List brands within the tenant.
    pub const PLATFORM_BRAND_READ_AT_TENANT: &'static str = "platform.brand.read@tenant";
    /// Create or update brands within the tenant.
    pub const PLATFORM_BRAND_WRITE_AT_TENANT: &'static str = "platform.brand.write@tenant";
    /// List locations within the tenant.
    pub const PLATFORM_LOCATION_READ_AT_TENANT: &'static str = "platform.location.read@tenant";
    /// Create or update locations.
    pub const PLATFORM_LOCATION_WRITE_AT_TENANT: &'static str = "platform.location.write@tenant";
    /// Pair a device to the authenticated user for PIN-only subsequent logins.
    pub const PLATFORM_DEVICE_AUTHORIZE_EXECUTE_AT_USER: &'static str = "platform.device.authorize.execute@user";
    /// Revoke a device binding for the authenticated user.
    pub const PLATFORM_DEVICE_UNBIND_DELETE_AT_USER: &'static str = "platform.device.unbind.delete@user";
    /// Read orders for the tenant.
    pub const COMMERCE_ORDER_READ_AT_TENANT: &'static str = "commerce.order.read@tenant";
    /// Create or update orders.
    pub const COMMERCE_ORDER_WRITE_AT_TENANT: &'static str = "commerce.order.write@tenant";
    /// Void or cancel orders.
    pub const COMMERCE_ORDER_DELETE_AT_TENANT: &'static str = "commerce.order.delete@tenant";
    /// Read customer records.
    pub const COMMERCE_CUSTOMER_READ_AT_TENANT: &'static str = "commerce.customer.read@tenant";
    /// Create or update customer records.
    pub const COMMERCE_CUSTOMER_WRITE_AT_TENANT: &'static str = "commerce.customer.write@tenant";
    /// Read inventory levels.
    pub const COMMERCE_INVENTORY_READ_AT_TENANT: &'static str = "commerce.inventory.read@tenant";
    /// Adjust inventory.
    pub const COMMERCE_INVENTORY_WRITE_AT_TENANT: &'static str = "commerce.inventory.write@tenant";
    /// Read product catalog.
    pub const COMMERCE_CATALOG_READ_AT_TENANT: &'static str = "commerce.catalog.read@tenant";
    /// Create or update products.
    pub const COMMERCE_CATALOG_WRITE_AT_TENANT: &'static str = "commerce.catalog.write@tenant";
    /// Invoke AI inference against the Ether router (chat, completion, embed).
    pub const AI_INFERENCE_EXECUTE_AT_TENANT: &'static str = "ai.inference.execute@tenant";
    /// Invoke an Ether-managed agent (Pantheon or custom).
    pub const AI_AGENT_EXECUTE_AT_TENANT: &'static str = "ai.agent.execute@tenant";
    /// Manage tenant-level AI model configuration (custom tiers, routing overrides).
    pub const AI_MODEL_ADMIN_AT_TENANT: &'static str = "ai.model.admin@tenant";
    /// Read payment records.
    pub const PAY_PAYMENT_READ_AT_TENANT: &'static str = "pay.payment.read@tenant";
    /// Initiate payment captures.
    pub const PAY_PAYMENT_WRITE_AT_TENANT: &'static str = "pay.payment.write@tenant";
    /// Issue refunds for captured payments.
    pub const PAY_REFUND_EXECUTE_AT_TENANT: &'static str = "pay.refund.execute@tenant";
    /// Read payout records.
    pub const PAY_PAYOUT_READ_AT_TENANT: &'static str = "pay.payout.read@tenant";
    /// Send transactional emails through Olympus Notify.
    pub const NOTIFY_EMAIL_WRITE_AT_TENANT: &'static str = "notify.email.write@tenant";
    /// Send SMS messages.
    pub const NOTIFY_SMS_WRITE_AT_TENANT: &'static str = "notify.sms.write@tenant";
    /// Send push notifications.
    pub const NOTIFY_PUSH_WRITE_AT_TENANT: &'static str = "notify.push.write@tenant";
    /// Register/deregister FCM device tokens for the authenticated user.
    pub const NOTIFY_DEVICES_WRITE_AT_USER: &'static str = "notify.devices.write@user";
    /// Subscribe the authenticated user's devices to public notification topics.
    pub const NOTIFY_TOPICS_SUBSCRIBE_AT_USER: &'static str = "notify.topics.subscribe@user";
    /// Subscribe arbitrary users/devices to privileged topics (e.g. role-gated topics).
    pub const NOTIFY_TOPICS_ADMIN_AT_TENANT: &'static str = "notify.topics.admin@tenant";
    /// Read domain events from the tenant's event stream.
    pub const EVENTS_STREAM_READ_AT_TENANT: &'static str = "events.stream.read@tenant";
    /// Publish domain events.
    pub const EVENTS_STREAM_WRITE_AT_TENANT: &'static str = "events.stream.write@tenant";
    /// Execute declarative queries against the tenant's data surface.
    pub const DATA_QUERY_EXECUTE_AT_TENANT: &'static str = "data.query.execute@tenant";
    /// Read pre-computed analytics cubes.
    pub const DATA_CUBE_READ_AT_TENANT: &'static str = "data.cube.read@tenant";
    /// Read files in tenant R2 buckets.
    pub const STORAGE_FILE_READ_AT_TENANT: &'static str = "storage.file.read@tenant";
    /// Upload or replace files.
    pub const STORAGE_FILE_WRITE_AT_TENANT: &'static str = "storage.file.write@tenant";
    /// Delete files.
    pub const STORAGE_FILE_DELETE_AT_TENANT: &'static str = "storage.file.delete@tenant";
    /// Read marketplace listings.
    pub const MARKETPLACE_LISTING_READ_AT_TENANT: &'static str = "marketplace.listing.read@tenant";
    /// Install or remove apps from the marketplace.
    pub const MARKETPLACE_INSTALL_WRITE_AT_TENANT: &'static str = "marketplace.install.write@tenant";
    /// Read active subscriptions.
    pub const BILLING_SUBSCRIPTION_READ_AT_TENANT: &'static str = "billing.subscription.read@tenant";
    /// Change subscription plan, add-ons, or quantity.
    pub const BILLING_SUBSCRIPTION_WRITE_AT_TENANT: &'static str = "billing.subscription.write@tenant";
    /// Read invoices.
    pub const BILLING_INVOICE_READ_AT_TENANT: &'static str = "billing.invoice.read@tenant";
    /// Read feature-gating policies.
    pub const GATING_POLICY_READ_AT_TENANT: &'static str = "gating.policy.read@tenant";
    /// Write feature-gating overrides.
    pub const GATING_POLICY_WRITE_AT_TENANT: &'static str = "gating.policy.write@tenant";
    /// Read registered kiosks.
    pub const DEVICES_KIOSK_READ_AT_TENANT: &'static str = "devices.kiosk.read@tenant";
    /// Register, configure, or pair kiosks.
    pub const DEVICES_KIOSK_WRITE_AT_TENANT: &'static str = "devices.kiosk.write@tenant";
    /// Register or reconfigure printers.
    pub const DEVICES_PRINTER_WRITE_AT_TENANT: &'static str = "devices.printer.write@tenant";
    /// Register cameras and configure vision pipelines.
    pub const DEVICES_CAMERA_ADMIN_AT_TENANT: &'static str = "devices.camera.admin@tenant";
    /// Read observability logs scoped to the tenant.
    pub const OBSERVE_LOG_READ_AT_TENANT: &'static str = "observe.log.read@tenant";
    /// Read metrics.
    pub const OBSERVE_METRIC_READ_AT_TENANT: &'static str = "observe.metric.read@tenant";
    /// Create or update alert rules.
    pub const OBSERVE_ALERT_WRITE_AT_TENANT: &'static str = "observe.alert.write@tenant";
    /// Read call records (metadata only, not transcripts).
    pub const VOICE_CALL_READ_AT_TENANT: &'static str = "voice.call.read@tenant";
    /// Place or modify voice calls.
    pub const VOICE_CALL_WRITE_AT_TENANT: &'static str = "voice.call.write@tenant";
    /// Read call transcripts.
    pub const VOICE_TRANSCRIPT_READ_AT_TENANT: &'static str = "voice.transcript.read@tenant";
    /// Provision, port, or release voice numbers.
    pub const VOICE_NUMBER_ADMIN_AT_TENANT: &'static str = "voice.number.admin@tenant";
    /// Configure voice agents (pipeline, prompts, fallback).
    pub const VOICE_AGENT_ADMIN_AT_TENANT: &'static str = "voice.agent.admin@tenant";
    /// Read the tenant's voice vocabulary (canonical terms, aliases, units).
    pub const VOICE_VOCABULARY_READ_AT_TENANT: &'static str = "voice.vocabulary.read@tenant";
    /// Create or update tenant-scoped voice vocabulary entries.
    pub const VOICE_VOCABULARY_WRITE_AT_TENANT: &'static str = "voice.vocabulary.write@tenant";
    /// Read the tenant's voice ordering rules (half-half, BYO, toppings).
    pub const VOICE_ORDERING_RULES_READ_AT_TENANT: &'static str = "voice.ordering_rules.read@tenant";
    /// Create, update, or replace tenant-scoped voice ordering rules.
    pub const VOICE_ORDERING_RULES_WRITE_AT_TENANT: &'static str = "voice.ordering_rules.write@tenant";
    /// Read agent-workflow runs.
    pub const WORKFLOWS_RUN_READ_AT_TENANT: &'static str = "workflows.run.read@tenant";
    /// Trigger agent-workflow runs.
    pub const WORKFLOWS_RUN_EXECUTE_AT_TENANT: &'static str = "workflows.run.execute@tenant";
    /// Create or update workflow definitions.
    pub const WORKFLOWS_DEFINITION_WRITE_AT_TENANT: &'static str = "workflows.definition.write@tenant";
    /// Read leads.
    pub const CONNECT_LEAD_READ_AT_TENANT: &'static str = "connect.lead.read@tenant";
    /// Create or update leads.
    pub const CONNECT_LEAD_WRITE_AT_TENANT: &'static str = "connect.lead.write@tenant";
    /// Read opportunities / deals.
    pub const CONNECT_OPPORTUNITY_READ_AT_TENANT: &'static str = "connect.opportunity.read@tenant";
    /// Create or update opportunities.
    pub const CONNECT_OPPORTUNITY_WRITE_AT_TENANT: &'static str = "connect.opportunity.write@tenant";
    /// Read external-IDP configuration.
    pub const IDENTITY_FEDERATION_READ_AT_TENANT: &'static str = "identity.federation.read@tenant";
    /// Configure SSO, SCIM, or external-IDP settings.
    pub const IDENTITY_FEDERATION_ADMIN_AT_TENANT: &'static str = "identity.federation.admin@tenant";
    /// Read camera analytics (counts, dwell time, events).
    pub const VISION_ANALYTICS_READ_AT_TENANT: &'static str = "vision.analytics.read@tenant";
    /// Run recognition models against camera feeds.
    pub const VISION_RECOGNITION_EXECUTE_AT_TENANT: &'static str = "vision.recognition.execute@tenant";
    /// Read message threads in the tenant's inbox.
    pub const MESSAGES_THREAD_READ_AT_TENANT: &'static str = "messages.thread.read@tenant";
    /// Send messages on behalf of the tenant.
    pub const MESSAGES_THREAD_WRITE_AT_TENANT: &'static str = "messages.thread.write@tenant";
    /// Read the caller's own inbox.
    pub const MESSAGES_INBOX_READ_AT_USER: &'static str = "messages.inbox.read@user";
    /// Forward-geocode a street address to lat/lng coordinates.
    pub const MAPS_GEOCODE_READ_AT_APP: &'static str = "maps.geocode.read@app";
    /// Reverse-geocode lat/lng coordinates (often from user device) to an address.
    pub const MAPS_REVERSE_GEOCODE_READ_AT_TENANT: &'static str = "maps.reverse_geocode.read@tenant";
    /// Validate whether an address or coordinate falls within configured delivery zones.
    pub const MAPS_DELIVERY_ZONE_EXECUTE_AT_TENANT: &'static str = "maps.delivery_zone.execute@tenant";
    /// Build a provider-specific directions URL (Waze / Google Maps / Apple Maps / OSM).
    pub const MAPS_DIRECTIONS_URL_READ_AT_APP: &'static str = "maps.directions_url.read@app";
    /// Read POS register state.
    pub const POS_REGISTER_READ_AT_TENANT: &'static str = "pos.register.read@tenant";
    /// Record POS transactions.
    pub const POS_TRANSACTION_WRITE_AT_TENANT: &'static str = "pos.transaction.write@tenant";
    /// Submit voice-originated orders to the POS.
    pub const POS_VOICE_ORDER_EXECUTE_AT_TENANT: &'static str = "pos.voice_order.execute@tenant";
    /// Read ad campaigns.
    pub const ADS_CAMPAIGN_READ_AT_TENANT: &'static str = "ads.campaign.read@tenant";
    /// Create or update ad campaigns.
    pub const ADS_CAMPAIGN_WRITE_AT_TENANT: &'static str = "ads.campaign.write@tenant";
    /// Read developer app records owned by the tenant.
    pub const DEVELOPER_APP_READ_AT_TENANT: &'static str = "developer.app.read@tenant";
    /// Submit, update, or publish developer apps.
    pub const DEVELOPER_APP_ADMIN_AT_TENANT: &'static str = "developer.app.admin@tenant";
    /// Read the caller's health/wellness records.
    pub const HEALTH_RECORD_READ_AT_USER: &'static str = "health.record.read@user";
    /// Add to the caller's health records.
    pub const HEALTH_RECORD_WRITE_AT_USER: &'static str = "health.record.write@user";
    /// Apply image transforms (sharpen, vibrant, social crop) to tenant media and persist a new derivative asset.
    pub const CREATOR_MEDIA_TRANSFORM_WRITE_AT_TENANT: &'static str = "creator.media.transform.write@tenant";
    /// Read the PizzaOS menu (items, categories, modifiers, price history).
    pub const PIZZA_MENU_READ_AT_TENANT: &'static str = "pizza.menu.read@tenant";
    /// Create or update menu items.
    pub const PIZZA_MENU_WRITE_AT_TENANT: &'static str = "pizza.menu.write@tenant";
    /// Read pizza orders.
    pub const PIZZA_ORDERS_READ_AT_TENANT: &'static str = "pizza.orders.read@tenant";
    /// Create or update pizza orders.
    pub const PIZZA_ORDERS_WRITE_AT_TENANT: &'static str = "pizza.orders.write@tenant";
    /// Issue refunds / void completed orders (hits pay.refund + commerce.cancelOrder).
    pub const PIZZA_ORDERS_REFUND_AT_TENANT: &'static str = "pizza.orders.refund@tenant";
    /// Read pizza customer records.
    pub const PIZZA_CUSTOMERS_READ_AT_TENANT: &'static str = "pizza.customers.read@tenant";
    /// Create or update customer records (addresses, caller-ID matches, notes).
    pub const PIZZA_CUSTOMERS_WRITE_AT_TENANT: &'static str = "pizza.customers.write@tenant";
    /// Read delivery zones.
    pub const PIZZA_DELIVERY_ZONES_READ_AT_TENANT: &'static str = "pizza.delivery_zones.read@tenant";
    /// Update delivery zones.
    pub const PIZZA_DELIVERY_ZONES_WRITE_AT_TENANT: &'static str = "pizza.delivery_zones.write@tenant";
    /// Read operating hours (consumed by menu board + customer app + phone-order flow).
    pub const PIZZA_HOURS_READ_AT_TENANT: &'static str = "pizza.hours.read@tenant";
    /// Update operating hours.
    pub const PIZZA_HOURS_WRITE_AT_TENANT: &'static str = "pizza.hours.write@tenant";
    /// Read loyalty program state (customer points, tiers, rewards).
    pub const PIZZA_LOYALTY_READ_AT_TENANT: &'static str = "pizza.loyalty.read@tenant";
    /// Adjust loyalty balances and rules.
    pub const PIZZA_LOYALTY_WRITE_AT_TENANT: &'static str = "pizza.loyalty.write@tenant";
    /// Read deals / promos (BOGO, % off, $ off, combos, time-window, day-of-week).
    pub const PIZZA_DEALS_READ_AT_TENANT: &'static str = "pizza.deals.read@tenant";
    /// Create or update deals + coupon codes.
    pub const PIZZA_DEALS_WRITE_AT_TENANT: &'static str = "pizza.deals.write@tenant";
    /// Administer deal budgets, redemption caps, corp-mandated deals (requires franchise trust).
    pub const PIZZA_DEALS_ADMIN_AT_TENANT: &'static str = "pizza.deals.admin@tenant";
    /// Read driver roster + current GPS/assignment state.
    pub const PIZZA_DRIVERS_READ_AT_TENANT: &'static str = "pizza.drivers.read@tenant";
    /// Dispatch drivers, update assignments, record deliveries.
    pub const PIZZA_DRIVERS_WRITE_AT_TENANT: &'static str = "pizza.drivers.write@tenant";
    /// Read KDS ticket queue, oven slot tracking, bump events.
    pub const PIZZA_KITCHEN_READ_AT_TENANT: &'static str = "pizza.kitchen.read@tenant";
    /// Bump tickets, update oven slots, invoke prep-forecast agent.
    pub const PIZZA_KITCHEN_WRITE_AT_TENANT: &'static str = "pizza.kitchen.write@tenant";
    /// Read owner analytics — food cost, labor %, review aggregates, demand anomalies (aggregated).
    pub const PIZZA_REPORTS_READ_AT_TENANT: &'static str = "pizza.reports.read@tenant";
    /// Read operational inventory state (86 list, waste log, real-time counts).
    pub const PIZZA_INVENTORY_READ_AT_TENANT: &'static str = "pizza.inventory.read@tenant";
    /// Mark items 86, log waste, adjust real-time counts.
    pub const PIZZA_INVENTORY_WRITE_AT_TENANT: &'static str = "pizza.inventory.write@tenant";
    /// Read aggregated review data (Google, Yelp, delivery platforms) + sentiment.
    pub const PIZZA_REVIEWS_READ_AT_TENANT: &'static str = "pizza.reviews.read@tenant";
    /// Draft or post review responses on behalf of the tenant.
    pub const PIZZA_REVIEWS_WRITE_AT_TENANT: &'static str = "pizza.reviews.write@tenant";
    /// Corporate franchise administration over location-tenants within the same company. Cross-tenant access is authorized via policy-layer company_id check (JWT.company_id must match target tenant's company_id). No @org holder in 1.0 — company scoping lives in policy layer, not claim layer. See pizza-os#77 reply for design call.
    pub const PIZZA_FRANCHISE_ADMIN_AT_TENANT: &'static str = "pizza.franchise.admin@tenant";
    /// Read OrderEchoAI orders (voice + chat originated).
    pub const ORDERECHO_ORDER_READ_AT_TENANT: &'static str = "orderecho.order.read@tenant";
    /// Submit or update orders.
    pub const ORDERECHO_ORDER_WRITE_AT_TENANT: &'static str = "orderecho.order.write@tenant";
    /// Cancel orders.
    pub const ORDERECHO_ORDER_CANCEL_AT_TENANT: &'static str = "orderecho.order.cancel@tenant";
    /// Read the OrderEchoAI-managed menu projection.
    pub const ORDERECHO_MENU_READ_AT_TENANT: &'static str = "orderecho.menu.read@tenant";
    /// Read customer profiles.
    pub const ORDERECHO_CUSTOMER_READ_AT_TENANT: &'static str = "orderecho.customer.read@tenant";
    /// Collect payment for voice orders.
    pub const ORDERECHO_PAYMENT_WRITE_AT_TENANT: &'static str = "orderecho.payment.write@tenant";
    /// Read voice transcripts captured by OrderEchoAI.
    pub const ORDERECHO_VOICE_TRANSCRIPT_READ_AT_TENANT: &'static str = "orderecho.voice.transcript.read@tenant";
    /// Read the bar menu.
    pub const BAR_MENU_READ_AT_TENANT: &'static str = "bar.menu.read@tenant";
    /// Update the bar menu.
    pub const BAR_MENU_WRITE_AT_TENANT: &'static str = "bar.menu.write@tenant";
    /// Read open and closed tabs.
    pub const BAR_TABS_READ_AT_TENANT: &'static str = "bar.tabs.read@tenant";
    /// Open, update, and close tabs.
    pub const BAR_TABS_WRITE_AT_TENANT: &'static str = "bar.tabs.write@tenant";
    /// Void tabs (compliance-audited).
    pub const BAR_TABS_VOID_AT_TENANT: &'static str = "bar.tabs.void@tenant";
    /// Read bar inventory.
    pub const BAR_INVENTORY_READ_AT_TENANT: &'static str = "bar.inventory.read@tenant";
    /// Adjust bar inventory.
    pub const BAR_INVENTORY_WRITE_AT_TENANT: &'static str = "bar.inventory.write@tenant";
    /// Update operating hours.
    pub const BAR_HOURS_WRITE_AT_TENANT: &'static str = "bar.hours.write@tenant";
    /// Record age verification events for legal compliance.
    pub const BAR_AGE_VERIFICATION_WRITE_AT_TENANT: &'static str = "bar.age_verification.write@tenant";
    /// Read bar loyalty program state.
    pub const BAR_LOYALTY_READ_AT_TENANT: &'static str = "bar.loyalty.read@tenant";
    /// Adjust loyalty balances and rules.
    pub const BAR_LOYALTY_WRITE_AT_TENANT: &'static str = "bar.loyalty.write@tenant";
    /// Update staff schedules.
    pub const BAR_STAFF_SCHEDULE_WRITE_AT_TENANT: &'static str = "bar.staff.schedule.write@tenant";
    /// Submit voice-originated bar orders.
    pub const BAR_VOICE_ORDER_EXECUTE_AT_TENANT: &'static str = "bar.voice.order.execute@tenant";
    /// Read the user's connected smart-home state.
    pub const AURA_SMART_HOME_READ_AT_USER: &'static str = "aura.smart_home.read@user";
    /// Control smart-home devices.
    pub const AURA_SMART_HOME_WRITE_AT_USER: &'static str = "aura.smart_home.write@user";
    /// Pair or remove smart-home devices and change automation rules.
    pub const AURA_SMART_HOME_ADMIN_AT_USER: &'static str = "aura.smart_home.admin@user";
    /// Read the user's calendar.
    pub const AURA_CALENDAR_READ_AT_USER: &'static str = "aura.calendar.read@user";
    /// Create or update calendar events.
    pub const AURA_CALENDAR_WRITE_AT_USER: &'static str = "aura.calendar.write@user";
    /// Read the user's messages (email, SMS snippets).
    pub const AURA_MESSAGES_READ_AT_USER: &'static str = "aura.messages.read@user";
    /// Read the user's current location.
    pub const AURA_LOCATION_READ_AT_USER: &'static str = "aura.location.read@user";
    /// Execute voice commands on the user's behalf (may trigger smart-home actions).
    pub const AURA_VOICE_COMMAND_EXECUTE_AT_USER: &'static str = "aura.voice.command.execute@user";
    /// Read the user's health and activity data.
    pub const AURA_HEALTH_READ_AT_USER: &'static str = "aura.health.read@user";
    /// Post or schedule posts to the user's connected third-party social accounts (Twitter/X, Instagram, Facebook, etc.). Requested per maximus-ai#35 2026-04-18.
    pub const AURA_SOCIAL_PUBLISH_AT_USER: &'static str = "aura.social.publish@user";
    /// Read CallStackAI call records.
    pub const CALLSTACK_CALL_READ_AT_TENANT: &'static str = "callstack.call.read@tenant";
    /// Place or manage calls via CallStackAI.
    pub const CALLSTACK_CALL_WRITE_AT_TENANT: &'static str = "callstack.call.write@tenant";
    /// Configure CallStack voice agents (prompts, escalation, on-call routing).
    pub const CALLSTACK_AGENT_ADMIN_AT_TENANT: &'static str = "callstack.agent.admin@tenant";
    /// Read creator media assets (list + get-by-id).
    pub const CREATOR_MEDIA_READ_AT_TENANT: &'static str = "creator.media.read@tenant";
    /// Update creator media metadata (doc_type + per-type structured fields).
    pub const CREATOR_MEDIA_UPDATE_AT_TENANT: &'static str = "creator.media.update@tenant";
    /// Soft-delete creator media assets (30-day grace window before purge).
    pub const CREATOR_MEDIA_DELETE_AT_TENANT: &'static str = "creator.media.delete@tenant";
    /// Permanently delete creator media assets immediately, bypassing the 30-day grace window.
    pub const CREATOR_MEDIA_HARD_DELETE_EXECUTE_AT_TENANT: &'static str = "creator.media.hard_delete.execute@tenant";
}

/// Every scope canonical string.
pub const OLYMPUS_SCOPES_ALL: [&str; 180] = [
    "auth.session.read@user",
    "auth.session.delete@user",
    "auth.mfa.write@user",
    "platform.tenant.read@tenant",
    "platform.tenant.write@tenant",
    "platform.tenant.admin@tenant",
    "platform.tenant.create@tenant",
    "platform.tenant.selfservice@user",
    "platform.tenant.lifecycle@tenant",
    "platform.tenant.retire@tenant",
    "platform.tenant.config.read@user",
    "platform.tenant.config.write@tenant",
    "platform.apps.install@tenant",
    "platform.apps.install.read@tenant",
    "platform.apps.uninstall@tenant",
    "platform.apps.manifest@user",
    "platform.tenant.secret.read@tenant",
    "platform.tenant.secret.write@tenant",
    "platform.tenant.secret.delete@tenant",
    "platform.tenant.secret.list.read@user",
    "platform.identity.invite.write@tenant",
    "platform.identity.invite.accept@user",
    "platform.identity.remove_from_tenant@tenant",
    "platform.firebase.exchange.execute@tenant",
    "platform.firebase.link.execute@user",
    "platform.user.profile.read@user",
    "platform.user.profile.write@user",
    "platform.user.read@tenant",
    "platform.user.write@tenant",
    "platform.user.delete@tenant",
    "platform.users.roles.assign.execute@tenant",
    "platform.brand.read@tenant",
    "platform.brand.write@tenant",
    "platform.location.read@tenant",
    "platform.location.write@tenant",
    "platform.device.authorize.execute@user",
    "platform.device.unbind.delete@user",
    "commerce.order.read@tenant",
    "commerce.order.write@tenant",
    "commerce.order.delete@tenant",
    "commerce.customer.read@tenant",
    "commerce.customer.write@tenant",
    "commerce.inventory.read@tenant",
    "commerce.inventory.write@tenant",
    "commerce.catalog.read@tenant",
    "commerce.catalog.write@tenant",
    "ai.inference.execute@tenant",
    "ai.agent.execute@tenant",
    "ai.model.admin@tenant",
    "pay.payment.read@tenant",
    "pay.payment.write@tenant",
    "pay.refund.execute@tenant",
    "pay.payout.read@tenant",
    "notify.email.write@tenant",
    "notify.sms.write@tenant",
    "notify.push.write@tenant",
    "notify.devices.write@user",
    "notify.topics.subscribe@user",
    "notify.topics.admin@tenant",
    "events.stream.read@tenant",
    "events.stream.write@tenant",
    "data.query.execute@tenant",
    "data.cube.read@tenant",
    "storage.file.read@tenant",
    "storage.file.write@tenant",
    "storage.file.delete@tenant",
    "marketplace.listing.read@tenant",
    "marketplace.install.write@tenant",
    "billing.subscription.read@tenant",
    "billing.subscription.write@tenant",
    "billing.invoice.read@tenant",
    "gating.policy.read@tenant",
    "gating.policy.write@tenant",
    "devices.kiosk.read@tenant",
    "devices.kiosk.write@tenant",
    "devices.printer.write@tenant",
    "devices.camera.admin@tenant",
    "observe.log.read@tenant",
    "observe.metric.read@tenant",
    "observe.alert.write@tenant",
    "voice.call.read@tenant",
    "voice.call.write@tenant",
    "voice.transcript.read@tenant",
    "voice.number.admin@tenant",
    "voice.agent.admin@tenant",
    "voice.vocabulary.read@tenant",
    "voice.vocabulary.write@tenant",
    "voice.ordering_rules.read@tenant",
    "voice.ordering_rules.write@tenant",
    "workflows.run.read@tenant",
    "workflows.run.execute@tenant",
    "workflows.definition.write@tenant",
    "connect.lead.read@tenant",
    "connect.lead.write@tenant",
    "connect.opportunity.read@tenant",
    "connect.opportunity.write@tenant",
    "identity.federation.read@tenant",
    "identity.federation.admin@tenant",
    "vision.analytics.read@tenant",
    "vision.recognition.execute@tenant",
    "messages.thread.read@tenant",
    "messages.thread.write@tenant",
    "messages.inbox.read@user",
    "maps.geocode.read@app",
    "maps.reverse_geocode.read@tenant",
    "maps.delivery_zone.execute@tenant",
    "maps.directions_url.read@app",
    "pos.register.read@tenant",
    "pos.transaction.write@tenant",
    "pos.voice_order.execute@tenant",
    "ads.campaign.read@tenant",
    "ads.campaign.write@tenant",
    "developer.app.read@tenant",
    "developer.app.admin@tenant",
    "health.record.read@user",
    "health.record.write@user",
    "creator.media.transform.write@tenant",
    "pizza.menu.read@tenant",
    "pizza.menu.write@tenant",
    "pizza.orders.read@tenant",
    "pizza.orders.write@tenant",
    "pizza.orders.refund@tenant",
    "pizza.customers.read@tenant",
    "pizza.customers.write@tenant",
    "pizza.delivery_zones.read@tenant",
    "pizza.delivery_zones.write@tenant",
    "pizza.hours.read@tenant",
    "pizza.hours.write@tenant",
    "pizza.loyalty.read@tenant",
    "pizza.loyalty.write@tenant",
    "pizza.deals.read@tenant",
    "pizza.deals.write@tenant",
    "pizza.deals.admin@tenant",
    "pizza.drivers.read@tenant",
    "pizza.drivers.write@tenant",
    "pizza.kitchen.read@tenant",
    "pizza.kitchen.write@tenant",
    "pizza.reports.read@tenant",
    "pizza.inventory.read@tenant",
    "pizza.inventory.write@tenant",
    "pizza.reviews.read@tenant",
    "pizza.reviews.write@tenant",
    "pizza.franchise.admin@tenant",
    "orderecho.order.read@tenant",
    "orderecho.order.write@tenant",
    "orderecho.order.cancel@tenant",
    "orderecho.menu.read@tenant",
    "orderecho.customer.read@tenant",
    "orderecho.payment.write@tenant",
    "orderecho.voice.transcript.read@tenant",
    "bar.menu.read@tenant",
    "bar.menu.write@tenant",
    "bar.tabs.read@tenant",
    "bar.tabs.write@tenant",
    "bar.tabs.void@tenant",
    "bar.inventory.read@tenant",
    "bar.inventory.write@tenant",
    "bar.hours.write@tenant",
    "bar.age_verification.write@tenant",
    "bar.loyalty.read@tenant",
    "bar.loyalty.write@tenant",
    "bar.staff.schedule.write@tenant",
    "bar.voice.order.execute@tenant",
    "aura.smart_home.read@user",
    "aura.smart_home.write@user",
    "aura.smart_home.admin@user",
    "aura.calendar.read@user",
    "aura.calendar.write@user",
    "aura.messages.read@user",
    "aura.location.read@user",
    "aura.voice.command.execute@user",
    "aura.health.read@user",
    "aura.social.publish@user",
    "callstack.call.read@tenant",
    "callstack.call.write@tenant",
    "callstack.agent.admin@tenant",
    "creator.media.read@tenant",
    "creator.media.update@tenant",
    "creator.media.delete@tenant",
    "creator.media.hard_delete.execute@tenant",
];
